import os
from setuptools import setup

here = os.path.abspath(os.path.dirname(__file__))


def read(fname):
    return open(os.path.join(here, fname)).read()


readme = read('README.md')

setup(
    name="gatelfdata",
    version="0.2",
    description="Library to handle the dense json data generated by the GATE Learning Framework",
    long_description=readme,
    author="Johann Petrak",
    author_email="johann.petrak@gmail.com",
    url="https://github.com/GateNLP/gate-lf-python-data",
    license="Apache 2.0",
    # keywords = "",
    packages=['gatelfdata'],
    py_modules=[],
    install_requires=["numpy"],
    python_requires=">=3",
    # package_data={'packagename': ['listof','relativefiles']}
    # py_modules=[]  # ????
    # scripts=['some.py'],
    # entry_points = {'console_scripts': ['some=some:main']},
    tests_require=['nose'],
    test_suite='nose.collector',
    classifiers=[],
)
